import React from "react";
import Head from "next/head";
function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <div className="p-4">
        <div className="container">
          <p>You&apos;re logged in with Next.js & JWT!!</p>
          <p>

          </p>
        </div>
      </div>
    </div>
  );
}

export default Home;
